# Generated by Django 5.0.6 on 2024-05-07 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="Carcase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carcase", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="Drive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drive", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="Engine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("engine", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="Generation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generation", models.CharField(max_length=60)),
                ("year_start", models.IntegerField()),
                ("year_end", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Transmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transmission", models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volume", models.DecimalField(decimal_places=1, max_digits=3)),
                ("year", models.IntegerField()),
                ("price_usd", models.DecimalField(decimal_places=2, max_digits=12)),
                ("description", models.TextField(blank=True)),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                ("region", models.CharField(max_length=60)),
                ("city", models.CharField(max_length=60)),
                ("av_id", models.IntegerField()),
                (
                    "carcase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="car_basa_api.carcase",
                    ),
                ),
                (
                    "drive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="car_basa_api.drive",
                    ),
                ),
                (
                    "engine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="car_basa_api.engine",
                    ),
                ),
                (
                    "generation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="car_basa_api.generation",
                    ),
                ),
                (
                    "transmission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="car_basa_api.transmission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("av_id", models.IntegerField()),
                ("mime_type", models.CharField()),
                ("is_main", models.BooleanField(default=False)),
                ("height_small", models.IntegerField()),
                ("width_small", models.IntegerField()),
                ("url_small", models.CharField()),
                ("height_big", models.IntegerField()),
                ("width_big", models.IntegerField()),
                ("url_big", models.CharField()),
                ("height_extrasmall", models.IntegerField()),
                ("width_extrasmall", models.IntegerField()),
                ("url_extrasmall", models.CharField()),
                ("height_medium", models.IntegerField()),
                ("width_medium", models.IntegerField()),
                ("url_medium", models.CharField()),
                (
                    "advertisement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="car_basa_api.advertisement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mark", models.CharField(max_length=60)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="car_basa_api.brand",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="generation",
            name="mark",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="car_basa_api.mark"
            ),
        ),
    ]
